

DEBUG_QUICKLY_LOCAL_GAME = False

DEBUG_HOLLOW_SHIPS = False
DEBUG_RESURRECT = False
DEBUG_HIT_BY = False


DEBUG_POINTS = []
DEBUG_SHOW_POINTS = False

DEBUG_SHOW_SPEED_VECTOR = False

DEBUG_FPS = False
DEBUG_KEYS = False


GAME_READY_MESSAGE = 'BE READY'
GAME_READY_PREAMBLE_FIRST = 'For first round'
GAME_READY_PREAMBLE_NEXT = 'For next round'
GAME_READY_PREAMBLE_LAST = 'For potentially last round'
GAME_DRAW_MESSAGE = 'DRAW'
GAME_DRAW_ROUND_MESSAGE = 'DRAW ROUND'
GAME_WINS_MESSAGE = 'WINS'
GAME_WINS_ROUND_MESSAGE = 'WINS ROUND'
